import assert from "node:assert/strict";
import { chmod, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import test from "node:test";
import { getMember, loadProject } from "../src/config.js";
import { buildCodexCommand, runCodexTask } from "../src/codex.js";
import { initProject } from "../src/init.js";
import { prepareMemberRuntime } from "../src/memberRuntime.js";
import { assemblePrompt } from "../src/prompt.js";
import { applyTaskPatch, delegateMember, getTask, interruptTask, readTaskPatch } from "../src/runtime.js";
import { createTask, readTask } from "../src/tasks.js";

const execFileAsync = promisify(execFile);

test("task creation writes inspectable files", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-task-"));
  try {
    await initProject(dir);
    const project = await loadProject(dir);
    const member = getMember(project, "backend");
    const runtime = await prepareMemberRuntime(project, member);
    const prompt = await assemblePrompt(project, member, runtime.settings, "lead", "inspect the repo");
    const task = await createTask(project, createTaskInput(runtime, "inspect the repo"), prompt);

    const saved = await readTask(project.projectRoot, task.id);
    assert.equal(saved.status, "queued");
    assert.equal(saved.assignee, "backend");
    assert.match(saved.prompt_path, /prompt\.md$/);
    assert.equal(saved.member_home_path, ".cofounder/members/backend/home");
    assert.equal(saved.member_settings_path, ".cofounder/members/backend/settings.toml");
    assert.equal(saved.member_effective_config_path, ".cofounder/members/backend/home/cofounder.effective.toml");
    assert.equal(saved.member_codex_config_path, ".cofounder/members/backend/home/config.toml");
    assert.equal(saved.work_mode, "direct");
    assert.equal(saved.cwd, dir);
    assert.equal(saved.execution_cwd, dir);
    assert.equal(saved.worktree_path, null);
    assert.deepEqual(saved.changed_files, []);
    assert.deepEqual(saved.new_changed_files, []);
    assert.deepEqual(saved.touched_files, []);
    assert.equal(saved.conflict_risk, false);

    const savedPrompt = await readFile(path.join(project.projectRoot, saved.prompt_path), "utf8");
    assert.match(savedPrompt, /Cofounder Delegated Task/);
    assert.match(savedPrompt, /inspect the repo/);

    const effectiveConfig = await readFile(path.join(project.projectRoot, saved.member_effective_config_path ?? ""), "utf8");
    assert.match(effectiveConfig, /Generated by Cofounder/);
    assert.match(effectiveConfig, /member = "backend"/);
    assert.match(effectiveConfig, /mcp_mode = "inherit"/);
    assert.match(effectiveConfig, /work_mode = "direct"/);

    const codexConfig = await readFile(path.join(project.projectRoot, saved.member_codex_config_path ?? ""), "utf8");
    assert.match(codexConfig, /Generated by Cofounder/);
    assert.match(codexConfig, /model = "gpt-5.5"/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("Codex command uses member settings", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-codex-"));
  try {
    await initProject(dir);
    const project = await loadProject(dir);
    const member = getMember(project, "backend");
    const runtime = await prepareMemberRuntime(project, member);
    const prompt = await assemblePrompt(project, member, runtime.settings, "lead", "inspect the repo");
    const task = await createTask(project, createTaskInput(runtime, "inspect the repo"), prompt);
    const command = buildCodexCommand(task, member, runtime.settings);

    assert.equal(command.command, "codex");
    assert.deepEqual(command.args.slice(0, 2), ["-a", "never"]);
    assert.deepEqual(command.args.slice(2, 6), ["exec", "--cd", dir, "--skip-git-repo-check"]);
    assert.equal(command.args.indexOf("-a"), 0);
    assert.ok(command.args.indexOf("-a") < command.args.indexOf("exec"));
    assert.ok(command.args.includes("-m"));
    assert.ok(command.args.includes("gpt-5.5"));
    assert.ok(command.args.includes("--json"));
    assert.equal(command.args.at(-1), "-");
    assert.equal(command.cwd, dir);
    assert.equal(command.env.CODEX_HOME, undefined);

    runtime.settings.runner = {
      codex: {
        ...runtime.settings.runner?.codex,
        use_member_home: true
      }
    };
    const memberHomeCommand = buildCodexCommand(task, member, runtime.settings);
    assert.equal(memberHomeCommand.env.CODEX_HOME, path.join(dir, ".cofounder/members/backend/home"));
    assert.equal(memberHomeCommand.cwd, dir);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("MCP allowlist generates isolated Codex config and command overrides", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-mcp-allow-"));
  try {
    await initProject(dir);
    await writeFile(path.join(dir, "base-codex.toml"), `model = "base-model"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.local]
command = "node"
args = ["server.js"]

[mcp_servers.local.env]
INLINE_SECRET = "do-not-copy"
`, "utf8");
    await writeFile(path.join(dir, ".cofounder/members/backend/settings.toml"), `model = "gpt-5.4-mini"
sandbox = "workspace-write"
approval = "never"
reasoning_effort = "medium"
live_interrupt = false

[mcp]
mode = "allowlist"
allow = ["linear", "local"]
config_path = "base-codex.toml"

[memory]
project = true
member = true
max_snippets = 5

[runner.codex]
json = true
extra_args = []
use_member_home = false
`, "utf8");

    const project = await loadProject(dir);
    const member = getMember(project, "backend");
    const runtime = await prepareMemberRuntime(project, member);
    const prompt = await assemblePrompt(project, member, runtime.settings, "lead", "inspect the repo");
    const task = await createTask(project, createTaskInput(runtime, "inspect the repo"), prompt);
    const command = buildCodexCommand(task, member, runtime.settings, runtime.codex_config);

    assert.equal(runtime.codex_config.mode, "allowlist");
    assert.equal(runtime.codex_config.isolated, true);
    assert.deepEqual(runtime.codex_config.allowed_servers, ["linear", "local"]);
    assert.deepEqual(command.args.slice(0, 2), ["-a", "never"]);
    assert.ok(command.args.indexOf("-a") < command.args.indexOf("exec"));
    assert.ok(command.args.includes("--ignore-user-config"));
    assert.ok(command.args.some((arg) => arg.includes("mcp_servers.linear.url")));
    assert.ok(command.args.some((arg) => arg.includes("mcp_servers.local.command")));
    assert.ok(!command.args.some((arg) => arg.includes("INLINE_SECRET")));

    const codexConfig = await readFile(path.join(project.projectRoot, runtime.member_codex_config_path ?? ""), "utf8");
    assert.match(codexConfig, /\[mcp_servers.linear\]/);
    assert.match(codexConfig, /\[mcp_servers.local\]/);
    assert.doesNotMatch(codexConfig, /INLINE_SECRET/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("MCP allowlist fails when a requested server is unavailable", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-mcp-missing-"));
  try {
    await initProject(dir);
    await writeFile(path.join(dir, "base-codex.toml"), `model = "base-model"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"
`, "utf8");
    await writeFile(path.join(dir, ".cofounder/members/backend/settings.toml"), `model = "gpt-5.4-mini"
sandbox = "workspace-write"
approval = "never"
reasoning_effort = "medium"
live_interrupt = false

[mcp]
mode = "allowlist"
allow = ["missing"]
config_path = "base-codex.toml"

[memory]
project = true
member = true
max_snippets = 5

[runner.codex]
json = true
extra_args = []
use_member_home = false
`, "utf8");

    const project = await loadProject(dir);
    const member = getMember(project, "backend");
    await assert.rejects(
      () => prepareMemberRuntime(project, member),
      /MCP server\(s\) not found/
    );
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("Codex runner records status, logs, and result with a fake codex binary", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-runner-"));
  const fakeBin = await mkdtemp(path.join(os.tmpdir(), "cofounder-fake-bin-"));
  const originalPath = process.env.PATH;

  try {
    const fakeCodexPath = path.join(fakeBin, "codex");
    await writeFile(fakeCodexPath, fakeCodexScript(), "utf8");
    await chmod(fakeCodexPath, 0o755);
    process.env.PATH = `${fakeBin}${path.delimiter}${originalPath ?? ""}`;

    await initProject(dir);
    const project = await loadProject(dir);
    const member = getMember(project, "backend");
    const runtime = await prepareMemberRuntime(project, member);
    const prompt = await assemblePrompt(project, member, runtime.settings, "lead", "inspect the repo");
    const task = await createTask(project, createTaskInput(runtime, "inspect the repo"), prompt);

    const finalTask = await runCodexTask(task, member, runtime.settings);

    assert.equal(finalTask.status, "succeeded");
    assert.equal(finalTask.exit_code, 0);
    assert.equal(finalTask.codex_session_id, "fake-session-123");

    const stdout = await readFile(path.join(project.projectRoot, finalTask.stdout_path), "utf8");
    const result = await readFile(path.join(project.projectRoot, finalTask.result_path), "utf8");
    const events = await readFile(path.join(project.projectRoot, finalTask.events_path), "utf8");

    assert.match(stdout, /fake codex received/);
    assert.match(result, /fake result/);
    assert.match(events, /task.status/);
    assert.match(events, /agent.message/);
    assert.match(events, /tool.call/);
  } finally {
    process.env.PATH = originalPath;
    await rm(dir, { recursive: true, force: true });
    await rm(fakeBin, { recursive: true, force: true });
  }
});

test("Codex runner records git changed files", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-git-files-"));
  const fakeBin = await mkdtemp(path.join(os.tmpdir(), "cofounder-git-bin-"));
  const originalPath = process.env.PATH;

  try {
    await initGitRepo(dir);
    const fakeCodexPath = path.join(fakeBin, "codex");
    await writeFile(fakeCodexPath, fakeCodexScript(), "utf8");
    await chmod(fakeCodexPath, 0o755);
    process.env.PATH = `${fakeBin}${path.delimiter}${originalPath ?? ""}`;

    await initProject(dir);
    await commitAll(dir, "cofounder init");
    const project = await loadProject(dir);
    const member = getMember(project, "backend");
    const runtime = await prepareMemberRuntime(project, member);
    const prompt = await assemblePrompt(project, member, runtime.settings, "lead", "write changed-file.txt");
    const task = await createTask(project, createTaskInput(runtime, "write changed-file.txt"), prompt);

    const finalTask = await runCodexTask(task, member, runtime.settings);

    assert.equal(finalTask.status, "succeeded");
    assert.equal(finalTask.git_available, true);
    assert.ok(finalTask.changed_files.includes("changed-file.txt"));
    assert.ok(finalTask.new_changed_files.includes("changed-file.txt"));
    assert.ok(finalTask.touched_files.includes("changed-file.txt"));
    assert.equal(finalTask.conflict_risk, false);
  } finally {
    process.env.PATH = originalPath;
    await rm(dir, { recursive: true, force: true });
    await rm(fakeBin, { recursive: true, force: true });
  }
});

test("Codex runner marks conflict risk when baseline dirty files remain dirty", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-git-risk-"));
  const fakeBin = await mkdtemp(path.join(os.tmpdir(), "cofounder-risk-bin-"));
  const originalPath = process.env.PATH;

  try {
    await initGitRepo(dir);
    await writeFile(path.join(dir, "tracked.txt"), "dirty before task\n", "utf8");
    const fakeCodexPath = path.join(fakeBin, "codex");
    await writeFile(fakeCodexPath, fakeCodexScript(), "utf8");
    await chmod(fakeCodexPath, 0o755);
    process.env.PATH = `${fakeBin}${path.delimiter}${originalPath ?? ""}`;

    await initProject(dir);
    const project = await loadProject(dir);
    const member = getMember(project, "backend");
    const runtime = await prepareMemberRuntime(project, member);
    const prompt = await assemblePrompt(project, member, runtime.settings, "lead", "write changed-file.txt");
    const task = await createTask(project, createTaskInput(runtime, "write changed-file.txt"), prompt);

    const finalTask = await runCodexTask(task, member, runtime.settings);

    assert.equal(finalTask.status, "succeeded");
    assert.ok(finalTask.base_changed_files.includes("tracked.txt"));
    assert.ok(finalTask.touched_files.includes("tracked.txt"));
    assert.equal(finalTask.conflict_risk, true);
  } finally {
    process.env.PATH = originalPath;
    await rm(dir, { recursive: true, force: true });
    await rm(fakeBin, { recursive: true, force: true });
  }
});

test("worktree tasks explain the git baseline prerequisite", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-worktree-no-git-"));
  try {
    await initProject(dir, { template: "worktree" });
    const project = await loadProject(dir);
    const member = getMember(project, "backend");
    const runtime = await prepareMemberRuntime(project, member);
    const prompt = await assemblePrompt(project, member, runtime.settings, "lead", "inspect the repo");

    await assert.rejects(
      () => createTask(project, createTaskInput(runtime, "inspect the repo"), prompt),
      /commit the baseline you want delegated agents to see/
    );
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("Codex runner can execute in an isolated git worktree", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-git-worktree-"));
  const fakeBin = await mkdtemp(path.join(os.tmpdir(), "cofounder-worktree-bin-"));
  const originalPath = process.env.PATH;

  try {
    await initGitRepo(dir);
    const fakeCodexPath = path.join(fakeBin, "codex");
    await writeFile(fakeCodexPath, fakeCodexScript(), "utf8");
    await chmod(fakeCodexPath, 0o755);
    process.env.PATH = `${fakeBin}${path.delimiter}${originalPath ?? ""}`;

    await initProject(dir);
    await writeFile(path.join(dir, ".cofounder/members/backend/settings.toml"), `model = "gpt-5.5"
sandbox = "workspace-write"
approval = "never"
reasoning_effort = "high"
live_interrupt = false

[write]
mode = "worktree"

[mcp]
mode = "inherit"
allow = []

[memory]
project = true
member = true
max_snippets = 5

[runner.codex]
json = true
extra_args = []
use_member_home = false
`, "utf8");

    const project = await loadProject(dir);
    const member = getMember(project, "backend");
    const runtime = await prepareMemberRuntime(project, member);
    const prompt = await assemblePrompt(project, member, runtime.settings, "lead", "write changed-file.txt");
    const task = await createTask(project, createTaskInput(runtime, "write changed-file.txt"), prompt);

    const finalTask = await runCodexTask(task, member, runtime.settings);

    assert.equal(finalTask.status, "succeeded");
    assert.equal(finalTask.work_mode, "worktree");
    assert.ok(finalTask.worktree_path);
    assert.equal(finalTask.execution_cwd, path.join(dir, finalTask.worktree_path));
    assert.ok(finalTask.changed_files.includes("changed-file.txt"));
    assert.ok(finalTask.new_changed_files.includes("changed-file.txt"));
    assert.match(await readFile(path.join(finalTask.execution_cwd, "changed-file.txt"), "utf8"), /changed by fake codex/);
    await assert.rejects(() => readFile(path.join(dir, "changed-file.txt"), "utf8"));

    const patch = await readTaskPatch(finalTask.id, dir);
    assert.match(patch, /diff --git a\/changed-file\.txt b\/changed-file\.txt/);

    const applyResult = await applyTaskPatch(finalTask.id, dir);
    assert.deepEqual(applyResult.files, ["changed-file.txt"]);
    assert.match(await readFile(path.join(dir, "changed-file.txt"), "utf8"), /changed by fake codex/);

    const appliedTask = await readTask(project.projectRoot, finalTask.id);
    assert.ok(appliedTask.applied_at);
    assert.equal(appliedTask.apply_patch_path, path.join(".cofounder", "runs", finalTask.id, "apply.patch"));
    assert.deepEqual(appliedTask.applied_files, ["changed-file.txt"]);
  } finally {
    process.env.PATH = originalPath;
    await rm(dir, { recursive: true, force: true });
    await rm(fakeBin, { recursive: true, force: true });
  }
});

test("interrupt cancels a running task and resumes the Codex session", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cofounder-interrupt-"));
  const fakeBin = await mkdtemp(path.join(os.tmpdir(), "cofounder-interrupt-bin-"));
  const originalPath = process.env.PATH;

  try {
    const fakeCodexPath = path.join(fakeBin, "codex");
    await writeFile(fakeCodexPath, fakeCodexScript(), "utf8");
    await chmod(fakeCodexPath, 0o755);
    process.env.PATH = `${fakeBin}${path.delimiter}${originalPath ?? ""}`;

    await initProject(dir);
    const runningTask = await delegateMember("backend", "stay running until interrupted", {
      caller: "lead",
      startDir: dir
    });
    const taskWithSession = await pollTask(dir, runningTask.id, (task) => Boolean(task.codex_session_id));

    const resumedTask = await interruptTask(taskWithSession.id, "finish after interrupt", dir);
    assert.equal(resumedTask.interrupted_task_id, taskWithSession.id);
    assert.equal(resumedTask.codex_resume_session_id, "fake-session-123");

    const cancelledTask = await getTask(taskWithSession.id, dir);
    assert.equal(cancelledTask.status, "cancelled");

    const completedResume = await pollTask(dir, resumedTask.id, (task) => task.status === "succeeded");
    assert.equal(completedResume.status, "succeeded");
    assert.equal(completedResume.codex_session_id, "fake-session-123");

    const result = await readFile(path.join(dir, completedResume.result_path), "utf8");
    assert.match(result, /fake resumed result/);
    const events = await readFile(path.join(dir, completedResume.events_path), "utf8");
    assert.match(events, /codex -a never exec resume/);
    assert.doesNotMatch(events, /codex exec resume .* -a never/);
  } finally {
    process.env.PATH = originalPath;
    await rm(dir, { recursive: true, force: true });
    await rm(fakeBin, { recursive: true, force: true });
  }
});

function fakeCodexScript(): string {
  return `#!/usr/bin/env node
const fs = require("node:fs");
const args = process.argv.slice(2);
const outputIndex = args.indexOf("--output-last-message");
const outputPath = outputIndex === -1 ? null : args[outputIndex + 1];
let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => {
  input += chunk;
});
process.stdin.on("end", () => {
  const execIndex = args.indexOf("exec");
  const isResume = execIndex !== -1 && args[execIndex + 1] === "resume";
  console.log(JSON.stringify({ type: "session_meta", payload: { id: "fake-session-123" } }));
  console.log(JSON.stringify({ type: "agent_message", message: "fake agent message" }));
  console.log(JSON.stringify({ type: "tool_call", message: "fake tool call" }));
  if (isResume) {
    if (outputPath) {
      fs.writeFileSync(outputPath, "fake resumed result\\n", "utf8");
    }
    console.log("fake codex resumed " + input.length + " chars");
    return;
  }
  if (input.includes("write changed-file.txt")) {
    fs.writeFileSync("changed-file.txt", "changed by fake codex\\n", "utf8");
  }
  if (input.includes("stay running")) {
    console.log("fake codex ready");
    setInterval(() => {}, 1000);
    return;
  }
  console.log("fake codex received " + input.length + " chars");
  if (outputPath) {
    fs.writeFileSync(outputPath, "fake result\\n", "utf8");
  }
});
`;
}

async function initGitRepo(dir: string): Promise<void> {
  await execFileAsync("git", ["init"], { cwd: dir });
  await execFileAsync("git", ["config", "user.email", "test@example.com"], { cwd: dir });
  await execFileAsync("git", ["config", "user.name", "Cofounder Test"], { cwd: dir });
  await writeFile(path.join(dir, "tracked.txt"), "clean\n", "utf8");
  await execFileAsync("git", ["add", "tracked.txt"], { cwd: dir });
  await execFileAsync("git", ["commit", "-m", "initial"], { cwd: dir });
}

async function commitAll(dir: string, message: string): Promise<void> {
  await execFileAsync("git", ["add", "."], { cwd: dir });
  await execFileAsync("git", ["commit", "-m", message], { cwd: dir });
}

function createTaskInput(runtime: Awaited<ReturnType<typeof prepareMemberRuntime>>, task: string) {
  return {
    caller: "lead",
    assignee: runtime.member.id,
    task,
    mode: "run" as const,
    member_home_path: runtime.member_home_path,
    member_prompt_path: runtime.member_prompt_path,
    member_settings_path: runtime.member_settings_path,
    member_effective_config_path: runtime.member_effective_config_path,
    member_codex_config_path: runtime.member_codex_config_path,
    work_mode: runtime.settings.write?.mode ?? "direct"
  };
}

async function pollTask(dir: string, taskId: string, predicate: (task: Awaited<ReturnType<typeof getTask>>) => boolean) {
  for (let attempt = 0; attempt < 40; attempt += 1) {
    const task = await getTask(taskId, dir);
    if (predicate(task)) {
      return task;
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  throw new Error(`Timed out waiting for task ${taskId}`);
}
