import { readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { parse as parseToml, stringify as stringifyToml } from "smol-toml";
import { CofounderError } from "./errors.js";
import { pathExists } from "./paths.js";
import type { LoadedProject, MemberDefinition, MemberSettings } from "./types.js";

export type McpMode = "inherit" | "none" | "allowlist";

export interface PreparedCodexConfig {
  mode: McpMode;
  config_path: string | null;
  allowed_servers: string[];
  isolated: boolean;
  override_args: string[];
}

export async function prepareCodexConfig(
  project: LoadedProject,
  member: MemberDefinition,
  settings: MemberSettings,
  memberHomeAbsolutePath: string | null
): Promise<PreparedCodexConfig> {
  const mode = settings.mcp?.mode ?? "inherit";
  const allowedServers = settings.mcp?.allow ?? [];
  validateMcpSettings(mode, allowedServers);

  const selectedServers = mode === "allowlist"
    ? await loadSelectedMcpServers(project, settings, allowedServers)
    : {};

  const codexConfig = buildCodexConfig(settings, selectedServers);
  let configPath: string | null = null;
  if (memberHomeAbsolutePath) {
    const configAbsolutePath = path.join(memberHomeAbsolutePath, "config.toml");
    await writeFile(configAbsolutePath, codexConfig, "utf8");
    configPath = path.relative(project.projectRoot, configAbsolutePath);
  }

  return {
    mode,
    config_path: configPath,
    allowed_servers: mode === "allowlist" ? allowedServers : [],
    isolated: mode !== "inherit",
    override_args: mode === "allowlist" ? buildMcpOverrideArgs(selectedServers) : []
  };
}

function validateMcpSettings(mode: McpMode, allowedServers: string[]): void {
  if (!["inherit", "none", "allowlist"].includes(mode)) {
    throw new CofounderError(`Unsupported MCP mode: ${mode}`);
  }

  if (mode !== "allowlist" && allowedServers.length > 0) {
    throw new CofounderError("mcp.allow can only be used when mcp.mode = \"allowlist\"");
  }

  for (const server of allowedServers) {
    if (!/^[A-Za-z0-9_-]+$/.test(server)) {
      throw new CofounderError(`Unsupported MCP server id: ${server}`);
    }
  }
}

async function loadSelectedMcpServers(
  project: LoadedProject,
  settings: MemberSettings,
  allowedServers: string[]
): Promise<Record<string, Record<string, unknown>>> {
  const configPath = resolveBaseCodexConfigPath(project, settings);
  if (!(await pathExists(configPath))) {
    throw new CofounderError(`Codex config not found for MCP allowlist: ${configPath}`);
  }

  const raw = await readFile(configPath, "utf8");
  const parsed = parseToml(raw) as unknown;
  const mcpServers = isRecord(parsed) && isRecord(parsed.mcp_servers) ? parsed.mcp_servers : {};
  const selected: Record<string, Record<string, unknown>> = {};
  const missing: string[] = [];

  for (const server of allowedServers) {
    const definition = mcpServers[server];
    if (!isRecord(definition)) {
      missing.push(server);
      continue;
    }
    selected[server] = sanitizeMcpServerDefinition(definition, settings.mcp?.include_inline_env === true);
  }

  if (missing.length > 0) {
    throw new CofounderError(`MCP server(s) not found in Codex config: ${missing.join(", ")}`);
  }

  return selected;
}

function resolveBaseCodexConfigPath(project: LoadedProject, settings: MemberSettings): string {
  if (settings.mcp?.config_path) {
    return path.isAbsolute(settings.mcp.config_path)
      ? settings.mcp.config_path
      : path.resolve(project.projectRoot, settings.mcp.config_path);
  }

  const codexHome = process.env.CODEX_HOME ? path.resolve(process.env.CODEX_HOME) : path.join(os.homedir(), ".codex");
  return path.join(codexHome, "config.toml");
}

function sanitizeMcpServerDefinition(definition: Record<string, unknown>, includeInlineEnv: boolean): Record<string, unknown> {
  const allowedKeys = [
    "url",
    "command",
    "args",
    "cwd",
    "bearer_token_env_var",
    "startup_timeout_sec",
    "tool_timeout_sec"
  ];
  const sanitized: Record<string, unknown> = {};

  for (const key of allowedKeys) {
    if (definition[key] !== undefined) {
      sanitized[key] = definition[key];
    }
  }

  if (includeInlineEnv && isRecord(definition.env)) {
    sanitized.env = definition.env;
  }

  return sanitized;
}

function buildCodexConfig(settings: MemberSettings, selectedServers: Record<string, Record<string, unknown>>): string {
  const config: Record<string, unknown> = {};
  if (settings.model) {
    config.model = settings.model;
  }
  if (settings.reasoning_effort) {
    config.model_reasoning_effort = settings.reasoning_effort;
  }
  if (Object.keys(selectedServers).length > 0) {
    config.mcp_servers = selectedServers;
  }

  return `# Generated by Cofounder. Do not put auth secrets here.\n${stringifyToml(config)}\n`;
}

function buildMcpOverrideArgs(selectedServers: Record<string, Record<string, unknown>>): string[] {
  const args: string[] = [];
  for (const [serverName, definition] of Object.entries(selectedServers)) {
    for (const [key, value] of Object.entries(definition)) {
      args.push("-c", `mcp_servers.${serverName}.${key}=${tomlValue(value)}`);
    }
  }
  return args;
}

function tomlValue(value: unknown): string {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(tomlValue).join(", ")}]`;
  }
  if (isRecord(value)) {
    const entries = Object.entries(value).map(([key, entryValue]) => `${key} = ${tomlValue(entryValue)}`);
    return `{ ${entries.join(", ")} }`;
  }
  throw new CofounderError(`Unsupported MCP config value: ${String(value)}`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
