import { mkdir, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { stringify as stringifyToml } from "smol-toml";
import { prepareCodexConfig, type PreparedCodexConfig } from "./codexConfig.js";
import { getMemberPaths, loadMemberSettings } from "./config.js";
import { CofounderError } from "./errors.js";
import { pathExists } from "./paths.js";
import { prepareSkills, type PreparedSkills } from "./skills.js";
import type { LoadedProject, MemberDefinition, MemberSettings } from "./types.js";

export interface PreparedMemberRuntime {
  member: MemberDefinition;
  settings: MemberSettings;
  member_home_path: string | null;
  member_prompt_path: string;
  member_settings_path: string;
  member_effective_config_path: string | null;
  member_codex_config_path: string | null;
  codex_config: PreparedCodexConfig;
  skills: PreparedSkills;
}

export async function prepareMemberRuntime(project: LoadedProject, member: MemberDefinition): Promise<PreparedMemberRuntime> {
  const settings = await loadMemberSettings(project, member);
  const paths = getMemberPaths(project, member);
  let effectiveConfigPath: string | null = null;
  let codexConfigPath: string | null = null;

  if (paths.homeAbsolutePath) {
    await mkdir(paths.homeAbsolutePath, { recursive: true });
  }

  const skills = await prepareSkills(project, settings, paths.homeAbsolutePath);
  const codexConfig = await prepareCodexConfig(project, member, settings, paths.homeAbsolutePath, {
    disabledSkillPaths: skills.disabled_project_skill_paths
  });
  codexConfigPath = codexConfig.config_path;
  if (skills.requires_member_home && codexConfig.mode === "inherit") {
    throw new CofounderError("skills.mode other than \"inherit\" requires explicit mcp.mode = \"isolated\" or \"none\" so member CODEX_HOME does not silently lose inherited MCP configuration");
  }
  if ((skills.requires_member_home || settings.runner?.codex?.use_member_home) && paths.homeAbsolutePath) {
    await prepareMemberCodexHome(paths.homeAbsolutePath);
  }

  if (paths.homeAbsolutePath) {
    const effectiveConfigAbsolutePath = path.join(paths.homeAbsolutePath, "cofounder.effective.toml");
    await writeFile(effectiveConfigAbsolutePath, buildEffectiveConfig(member, settings, codexConfig, skills), "utf8");
    effectiveConfigPath = path.relative(project.projectRoot, effectiveConfigAbsolutePath);
  }

  return {
    member,
    settings,
    member_home_path: paths.homePath,
    member_prompt_path: paths.promptPath,
    member_settings_path: paths.settingsPath,
    member_effective_config_path: effectiveConfigPath,
    member_codex_config_path: codexConfigPath,
    codex_config: codexConfig,
    skills
  };
}

function buildEffectiveConfig(
  member: MemberDefinition,
  settings: MemberSettings,
  codexConfig: PreparedCodexConfig,
  skills: PreparedSkills
): string {
  const codex: Record<string, unknown> = {};
  if (settings.model) {
    codex["model"] = settings.model;
  }
  if (settings.reasoning_effort) {
    codex["model_reasoning_effort"] = settings.reasoning_effort;
  }

  const cofounder: Record<string, unknown> = {
    member: member.id,
    runner: member.runner,
    codex_config_path: codexConfig.config_path ?? "",
    mcp_mode: codexConfig.mode,
    mcp_allowed_servers: codexConfig.allowed_servers,
    mcp_from_main_servers: codexConfig.from_main_servers,
    mcp_team_servers: codexConfig.team_servers,
    mcp_oauth_credentials_store: codexConfig.oauth_credentials_store ?? "",
    mcp_isolated: codexConfig.isolated,
    work_mode: settings.write?.mode ?? "direct",
    skill_mode: skills.mode,
    skill_from_project: skills.from_project,
    skill_from_main: skills.from_main,
    skill_team: skills.team,
    disabled_project_skill_paths: skills.disabled_project_skill_paths,
    skill_requires_member_home: skills.requires_member_home,
    skill_agent_root: skills.agent_skill_root ?? "",
    skill_codex_root: skills.codex_skill_root ?? ""
  };
  if (settings.sandbox) {
    cofounder["sandbox"] = settings.sandbox;
  }
  if (settings.approval) {
    cofounder["approval"] = settings.approval;
  }
  if (settings.live_interrupt !== undefined) {
    cofounder["live_interrupt"] = settings.live_interrupt;
  }

  const runnerCodex = settings.runner?.codex ?? {};
  const config = {
    codex,
    cofounder,
    write: settings.write ?? { mode: "direct" },
    memory: settings.memory ?? {},
    skills: settings.skills ?? {},
    runner: {
      codex: runnerCodex
    }
  };

  return `# Generated by Cofounder. Inspectable runtime settings; not used as Codex auth storage.\n${stringifyToml(config)}\n`;
}

async function prepareMemberCodexHome(memberHomeAbsolutePath: string): Promise<void> {
  await mkdir(memberHomeAbsolutePath, { recursive: true });
  const sourceCodexHome = process.env["CODEX_HOME"]
    ? path.resolve(process.env["CODEX_HOME"])
    : path.join(os.homedir(), ".codex");
  const sourceAuthPath = path.join(sourceCodexHome, "auth.json");
  const targetAuthPath = path.join(memberHomeAbsolutePath, "auth.json");

  if (!(await pathExists(sourceAuthPath)) || await pathExists(targetAuthPath)) {
    return;
  }

  try {
    await symlink(sourceAuthPath, targetAuthPath);
  } catch (error) {
    throw new CofounderError(`Could not link Codex auth into member home: ${(error as Error).message}`);
  }
}
