import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { stringify as stringifyToml } from "smol-toml";
import { prepareCodexConfig, type PreparedCodexConfig } from "./codexConfig.js";
import { getMemberPaths, loadMemberSettings } from "./config.js";
import type { LoadedProject, MemberDefinition, MemberSettings } from "./types.js";

export interface PreparedMemberRuntime {
  member: MemberDefinition;
  settings: MemberSettings;
  member_home_path: string | null;
  member_prompt_path: string;
  member_settings_path: string;
  member_effective_config_path: string | null;
  member_codex_config_path: string | null;
  codex_config: PreparedCodexConfig;
}

export async function prepareMemberRuntime(project: LoadedProject, member: MemberDefinition): Promise<PreparedMemberRuntime> {
  const settings = await loadMemberSettings(project, member);
  const paths = getMemberPaths(project, member);
  let effectiveConfigPath: string | null = null;
  let codexConfigPath: string | null = null;

  if (paths.homeAbsolutePath) {
    await mkdir(paths.homeAbsolutePath, { recursive: true });
  }

  const codexConfig = await prepareCodexConfig(project, member, settings, paths.homeAbsolutePath);
  codexConfigPath = codexConfig.config_path;

  if (paths.homeAbsolutePath) {
    const effectiveConfigAbsolutePath = path.join(paths.homeAbsolutePath, "cofounder.effective.toml");
    await writeFile(effectiveConfigAbsolutePath, buildEffectiveConfig(member, settings, codexConfig), "utf8");
    effectiveConfigPath = path.relative(project.projectRoot, effectiveConfigAbsolutePath);
  }

  return {
    member,
    settings,
    member_home_path: paths.homePath,
    member_prompt_path: paths.promptPath,
    member_settings_path: paths.settingsPath,
    member_effective_config_path: effectiveConfigPath,
    member_codex_config_path: codexConfigPath,
    codex_config: codexConfig
  };
}

function buildEffectiveConfig(member: MemberDefinition, settings: MemberSettings, codexConfig: PreparedCodexConfig): string {
  const codex: Record<string, unknown> = {};
  if (settings.model) {
    codex.model = settings.model;
  }
  if (settings.reasoning_effort) {
    codex.model_reasoning_effort = settings.reasoning_effort;
  }

  const cofounder: Record<string, unknown> = {
    member: member.id,
    runner: member.runner,
    codex_config_path: codexConfig.config_path ?? "",
    mcp_mode: codexConfig.mode,
    mcp_allowed_servers: codexConfig.allowed_servers,
    mcp_isolated: codexConfig.isolated,
    work_mode: settings.write?.mode ?? "direct"
  };
  if (settings.sandbox) {
    cofounder.sandbox = settings.sandbox;
  }
  if (settings.approval) {
    cofounder.approval = settings.approval;
  }
  if (settings.live_interrupt !== undefined) {
    cofounder.live_interrupt = settings.live_interrupt;
  }

  const runnerCodex = settings.runner?.codex ?? {};
  const config = {
    codex,
    cofounder,
    write: settings.write ?? { mode: "direct" },
    memory: settings.memory ?? {},
    runner: {
      codex: runnerCodex
    }
  };

  return `# Generated by Cofounder. Inspectable runtime settings; not used as Codex auth storage.\n${stringifyToml(config)}\n`;
}
